services:

  mysql:
    image: mysql:8.0
    container_name: url-shortener-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortener

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: url-shortener-backend

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/url_shortener
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      JWT_SECRET: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJqYW52aUB0ZXN0LmNvbSIsInVzZXJJZCI6MSwiaWF0IjoxNzg0MzAyNTUxLCJleHAiOjE3ODQzODg5NTF9.I6RYQVc9qCYo2_QkvmbuAztB1eGVUDpuGBSNb_bl1zrBNhNq0QxX9wopvSoEdaWK

volumes:
  mysql-data: